---
language: python
python: 
  - "2.7"
  - "3.6"

sudo: false

# Install python-pip
addons:
  apt:
    packages:
    - python-pip
    - aspell
    - aspell-en

install:
  # Install ansible
  - pip install ansible
  - pip install ansible-lint
  - pip install ansible-review

  # Check ansible version
  - ansible --version

  # Link github repo to ansible-galaxy name
  - ln -s  $PWD ../while_true_do.yum-cron

# Run the tests
script:
  - chmod +x tests/test-ansible.sh
  - tests/test-ansible.sh
  - chmod +x tests/test-spelling.sh
  - tests/test-spelling.sh

notifications:
  webhooks:
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/
    on_success: always
    on_failure: never
    on_pull_requests: false
